### PR TITLE
Fixed cookiejar error

### LINKED ISSUE #30: recon/domains-hosts/netcraft - Not working
```
[recon-ng][default] > marketplace install recon/domains-hosts/netcraft
[*] Module installed: recon/domains-hosts/netcraft
[*] Reloading modules...
[recon-ng][default] > modules load recon/domains-hosts/netcraft
[recon-ng][default][netcraft] > info

      Name: Netcraft Hostname Enumerator
    Author: thrapt (thrapt@gmail.com)
   Version: 1.0

Description:
  Harvests hosts from Netcraft.com. Updates the 'hosts' table with the results.

Options:
  Name    Current Value  Required  Description
  ------  -------------  --------  -----------
  SOURCE  default        yes       source of input (see 'show info' for details)

Source Options:
  default        SELECT DISTINCT domain FROM domains WHERE domain IS NOT NULL
  <string>       string representing a single input
  <path>         path to a file containing a list of inputs
  query <sql>    database query returning one column of inputs

[recon-ng][default][netcraft] > run
[!] 'Response' object has no attribute 'cookiejar'.
[!] Something broken? See https://github.com/lanmaster53/recon-ng/wiki/Troubleshooting#issue-reporting.
```

### PR DESCRIPTION
**Pull request by cam-barts**
**Before submitting a pull request, make sure to complete the following:**
- [x] Ensure there are no similar pull requests.
- [x] Read the [Development Guide](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide).

**What kind of PR is this?**  
_Please add an 'x' in the appropriate box, and apply a label to the PR matching the type here._
- [x] Bug Fix
- [ ] New Module
- [ ] Documentation Update

**Checklist For Approval**
- [x] Updated the meta dictionary for the module.
  - If bug fix, updated the version.
- [x] Indexed the module
- [x] Added the index to the `modules.yml` file
- [x] Made the most out of the available [mixins](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide#mixins).
- [x] Ensured the code is PEP8 compliant with `pycodestyle` or `black`.

Closes #30 for those silly gooses asking for an update

### CODE REVIEW

**Comment by MrJester** [comment]
This does not fix the underlying problem. Netcraft has updated the website and the parser is no longer extracting the hosts from the page that it pulls down. If you use your updated module try using a SOURCE of example.com or paypal.com the hosts table should be updated with what is found yet nothing is populated. Need to go in and update the parsing.

**Comment by cam-barts** [comment]
Oh no! Now I'm the silly goose for not looking into what the actual problem was! I think this fixed it though. Seemed to work out okay with some test input.

**Comment by MrJester** [comment]
Yep there we go. @lanmaster53 I tested this and it does fix the issues we were having. Should be G2G to merge.

**Comment by tamnol** [comment]
Hi **@MrJester**, it trying to fix this issue locally but it looks like you and others have been back and forth discussing on the issue and ultimately, you got it right. So would you mind providing more details on how you did it? for **Cam-barts** hasn't merged the branch yet. 
Thanks

**Comment by MrJester** [comment]
@tamnol look at the code that I approved it will show you the working changes. Waiting on Tim to approve and push this to the master branch.

**Pull request merged**
