### PR TITLE
Update profiler.py (wmn-data.json all valid parameter is removed)

### PR DESCRIPTION
**Pull request by guodong000**
**Before submitting a pull request, make sure to complete the following:**
- [x] Ensure there are no similar pull requests.
- [x] Read the [Development Guide](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide).

**What kind of PR is this?**  
_Please add an 'x' in the appropriate box, and apply a label to the PR matching the type here._
- [x] Bug Fix
- [ ] New Module
- [ ] Documentation Update

**Checklist For Approval**
- [x] Updated the meta dictionary for the module.
  - If bug fix, updated the version.
- [ ] Indexed the module
- [x] Added the index to the `modules.yml` file
- [ ] Made the most out of the available [mixins](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide#mixins).
- [ ] Ensured the code is PEP8 compliant with `pycodestyle` or `black`.

### CODE REVIEW

**Comment by guodong000** [comment]
WhatsMyName JSON Scheme Changes PR:
https://github.com/WebBreacher/WhatsMyName/issues/738#issue-1824971152

**Comment by wolfsoldier47** [comment]
Just tested it and its working  ! thanks mate !

**Comment by JacopIsOk** [comment]
Still having this issue. Getting loads of red text when running the profiler module.

**Review by NickBohannan — APPROVED** [review]
Can confirm this change solves the valid errors when running profiler.

**Comment by Felipe-CR** [comment]
No logro conseguir la actualizacion para que me funcione el profiler

**Comment by selkirk416** [comment]
Hopefully a reviewer can approve this. It fixes a bug that still persists.

**Comment by h4cks1lv3r** [comment]
Tried running profiler and receive the same errors as described by other users.

**Pull request merged**
