### PR TITLE
Fixed title.

### PR DESCRIPTION
**Pull request by leebaird**
**Before submitting a pull request, make sure to complete the following:**
- [ ] Ensure there are no similar pull requests.
- [ ] Read the [Development Guide](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide).

**What kind of PR is this?**  
_Please add an 'x' in the appropriate box, and apply a label to the PR matching the type here._
- [ ] Bug Fix
- [ ] New Module
- [ ] Documentation Update

**Checklist For Approval**
- [ ] Updated the meta dictionary for the module.
  - If bug fix, updated the version.
- [ ] Indexed the module
- [ ] Added the index to the `modules.yml` file
- [ ] Made the most out of the available [mixins](https://github.com/lanmaster53/recon-ng/wiki/Development-Guide#mixins).
- [ ] Ensured the code is PEP8 compliant with `pycodestyle` or `black`.

### CODE REVIEW

**Comment by MrJester** [comment]
Remove the comma at the end of line 84

**Comment by MrJester** [comment]
Could you remove the edits from README. Keep the PRs to just the issue at hand. Thanks

**Comment by MrJester** [comment]
You have a bunch of extra files within this PR that need to be removed. Lets keep this to Hunter.io

**Comment by lanmaster53** [comment]
This is a mess. I don't capitalize comments because that's my personal style. No need for these changes.

**Pull request closed without merging**
